-- Create the 'sponsors' table if it doesn't already exist
-- (This stores sponsor profile information)
CREATE TABLE IF NOT EXISTS public.sponsors (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    full_name TEXT,
    email TEXT UNIQUE,
    phone_number TEXT,
    address TEXT,
    approval_status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security on sponsors
ALTER TABLE public.sponsors ENABLE ROW LEVEL SECURITY;

-- Policy: Sponsors can insert their own profile
CREATE POLICY "Sponsors can insert their own profile" 
ON public.sponsors FOR INSERT 
WITH CHECK (auth.uid() = id);

-- Policy: Sponsors can view their own profile
CREATE POLICY "Sponsors can view their own profile" 
ON public.sponsors FOR SELECT 
USING (auth.uid() = id);

-- Policy: Sponsors can update their own profile
CREATE POLICY "Sponsors can update their own profile" 
ON public.sponsors FOR UPDATE 
USING (auth.uid() = id);


-- Create the 'sponsor_vehicle_requests' table
-- (This acts as the staging area for vehicle approvals)
CREATE TABLE IF NOT EXISTS public.sponsor_vehicle_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    sponsor_id UUID REFERENCES public.sponsors(id) NOT NULL,
    vehicle_type TEXT NOT NULL, -- 'bike', 'car', 'scooty'
    vehicle_details JSONB NOT NULL, -- Stores name, price, images, description, etc.
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected'))
);

-- Enable Row Level Security
ALTER TABLE public.sponsor_vehicle_requests ENABLE ROW LEVEL SECURITY;

-- Policy: Sponsors can insert their own requests
CREATE POLICY "Sponsors can insert their own requests" 
ON public.sponsor_vehicle_requests FOR INSERT 
WITH CHECK (auth.uid() = sponsor_id);

-- Policy: Sponsors can view their own requests
CREATE POLICY "Sponsors can view their own requests" 
ON public.sponsor_vehicle_requests FOR SELECT 
USING (auth.uid() = sponsor_id);

-- Policy: Admins (Service Role) can do everything
-- (Note: Service role bypasses RLS, but if you have an admin user authenticated via client, you might need a policy for them)
-- For now, we assume Admin Panel uses Service Role or a specific admin flag.
