-- Create withdrawal_requests table
CREATE TABLE IF NOT EXISTS public.withdrawal_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    sponsor_id UUID REFERENCES public.sponsors(id) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    payment_method TEXT NOT NULL CHECK (payment_method IN ('bank', 'upi')),
    
    -- Bank details (if payment_method = 'bank')
    bank_account_number TEXT,
    ifsc_code TEXT,
    account_holder_name TEXT,
    
    -- UPI details (if payment_method = 'upi')
    upi_id TEXT,
    
    -- Request status
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'completed')),
    
    -- Admin notes and processing
    admin_notes TEXT,
    processed_by UUID REFERENCES auth.users(id),
    processed_at TIMESTAMP WITH TIME ZONE,
    
    -- Transaction reference
    transaction_reference TEXT,
    
    CONSTRAINT valid_bank_details CHECK (
        (payment_method = 'bank' AND bank_account_number IS NOT NULL AND ifsc_code IS NOT NULL AND account_holder_name IS NOT NULL)
        OR
        (payment_method = 'upi' AND upi_id IS NOT NULL)
    )
);

-- Enable Row Level Security
ALTER TABLE public.withdrawal_requests ENABLE ROW LEVEL SECURITY;

-- Policy: Sponsors can insert their own withdrawal requests
CREATE POLICY "Sponsors can insert their own withdrawal requests" 
ON public.withdrawal_requests FOR INSERT 
WITH CHECK (auth.uid() = sponsor_id);

-- Policy: Sponsors can view their own withdrawal requests
CREATE POLICY "Sponsors can view their own withdrawal requests" 
ON public.withdrawal_requests FOR SELECT 
USING (auth.uid() = sponsor_id);

-- Policy: Service role can do everything (for admin operations)
-- Note: Service role bypasses RLS automatically

-- Add bank and UPI columns to sponsors table if they don't exist
ALTER TABLE public.sponsors 
ADD COLUMN IF NOT EXISTS bank_account_number TEXT,
ADD COLUMN IF NOT EXISTS ifsc_code TEXT,
ADD COLUMN IF NOT EXISTS account_holder_name TEXT,
ADD COLUMN IF NOT EXISTS upi_id TEXT;

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_sponsor_id ON public.withdrawal_requests(sponsor_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_status ON public.withdrawal_requests(status);
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_created_at ON public.withdrawal_requests(created_at DESC);
