import React from 'react';
import { ShieldCheck, FileText, AlertCircle, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

const TermsConditions = () => {
    return (
        <div className="min-h-screen bg-slate-50 font-sans text-slate-800 pb-20">
            {/* Header */}
            <div className="bg-white border-b border-slate-200 sticky top-0 z-10">
                <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <Link to="/dashboard" className="p-2 -ml-2 text-slate-400 hover:text-slate-600 hover:bg-slate-100 rounded-full transition-colors">
                            <ArrowLeft className="w-5 h-5" />
                        </Link>
                        <h1 className="text-xl font-bold text-slate-900">Terms & Conditions</h1>
                    </div>
                    <div className="flex items-center gap-2 text-sm text-slate-500">
                        <ShieldCheck className="w-4 h-4 text-brand-500" />
                        <span>Sponsor Agreement</span>
                    </div>
                </div>
            </div>

            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10">

                {/* Intro Card */}
                <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8 mb-8">
                    <div className="flex items-start gap-4">
                        <div className="p-3 bg-brand-50 rounded-xl text-brand-600 shrink-0">
                            <FileText className="w-8 h-8" />
                        </div>
                        <div>
                            <h2 className="text-2xl font-bold text-slate-900 mb-2">RentHub Sponsor Agreement</h2>
                            <p className="text-slate-600 leading-relaxed">
                                Welcome to the RentHub Sponsor Program. By listing your vehicle on our platform, you agree to the following terms and conditions. These terms ensure a safe, transparent, and profitable experience for all parties involved.
                            </p>
                            <div className="mt-4 text-xs font-semibold uppercase tracking-wider text-slate-400">
                                Last Updated: February 2026
                            </div>
                        </div>
                    </div>
                </div>

                {/* Content Sections */}
                <div className="space-y-6">

                    {/* Section 1 */}
                    <Section title="1. Vehicle Eligibility & Listing">
                        <ul className="list-disc pl-5 space-y-2 text-slate-600">
                            <li>All vehicles must be registered, insured, and in good working condition.</li>
                            <li>Sponsors must provide accurate details, photos, and documentation (RC, Insurance, PUC) for each vehicle.</li>
                            <li>RentHub reserves the right to reject or delist vehicles that do not meet safety or quality standards.</li>
                            <li>Vehicles must be available for booking during the availability windows set by the Sponsor.</li>
                        </ul>
                    </Section>

                    {/* Section 2 */}
                    <Section title="2. Earnings & Payouts">
                        <ul className="list-disc pl-5 space-y-2 text-slate-600">
                            <li>Sponsors earn <strong>70%</strong> of the total booking revenue generated by their vehicles. RentHub retains a <strong>30%</strong> platform fee.</li>
                            <li>Payouts are processed daily/weekly upon request via the "Withdrawal" section.</li>
                            <li>Earnings are calculated based on completed rides. Cancelled rides may be subject to different policies.</li>
                            <li>RentHub is not responsible for tax liabilities incurred by the Sponsor's earnings.</li>
                        </ul>
                    </Section>

                    {/* Section 3 */}
                    <Section title="3. Maintenance & Damages">
                        <ul className="list-disc pl-5 space-y-2 text-slate-600">
                            <li>Sponsors are responsible for the general maintenance and servicing of their vehicles.</li>
                            <li>In case of damage during a ride, RentHub will facilitate the recovery process from the user or insurance, but the Sponsor is ultimately responsible for the vehicle's condition.</li>
                            <li>Minor wear and tear is expected and not covered under damage claims.</li>
                            <li>Users are required to report any issues before starting a ride.</li>
                        </ul>
                    </Section>

                    {/* Section 4 */}
                    <Section title="4. Sponsor Responsibilities">
                        <ul className="list-disc pl-5 space-y-2 text-slate-600">
                            <li>Ensure the vehicle has sufficient fuel/charge at the start of each booking.</li>
                            <li>Hand over the vehicle keys and documents (if physical handover is required) promptly.</li>
                            <li>Respond to booking requests and user queries in a timely manner.</li>
                            <li>Prohibit the use of vehicles for illegal activities.</li>
                        </ul>
                    </Section>

                    {/* Section 5 */}
                    <Section title="5. Platform Policies">
                        <ul className="list-disc pl-5 space-y-2 text-slate-600">
                            <li>RentHub may suspend or terminate Sponsor accounts for violation of terms, fraudulent activity, or poor service quality.</li>
                            <li>Sponsors must not solicit RentHub users to book directly outside the platform.</li>
                            <li>We respect your privacy and data. Please refer to our Privacy Policy for more details.</li>
                        </ul>
                    </Section>

                </div>

                {/* Disclaimer */}
                <div className="mt-10 p-4 bg-orange-50 border border-orange-100 rounded-xl flex gap-3 text-sm text-orange-800">
                    <AlertCircle className="w-5 h-5 shrink-0" />
                    <p>
                        These terms are subject to change. RentHub will notify sponsors of any significant updates. Continued use of the platform constitutes acceptance of the new terms.
                    </p>
                </div>

            </div>
        </div>
    );
};

const Section = ({ title, children }) => (
    <div className="bg-white rounded-xl shadow-sm border border-slate-100 overflow-hidden">
        <div className="px-6 py-4 border-b border-slate-50 bg-slate-50/50">
            <h3 className="font-bold text-slate-800">{title}</h3>
        </div>
        <div className="p-6">
            {children}
        </div>
    </div>
);

export default TermsConditions;
